/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZarejestrujRouteImport } from './routes/zarejestruj'
import { Route as ZalogujRouteImport } from './routes/zaloguj'
import { Route as UzytkownicyRouteImport } from './routes/uzytkownicy'
import { Route as UlepszRouteImport } from './routes/ulepsz'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as DodajRouteImport } from './routes/dodaj'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatekIdRouteImport } from './routes/watek.$id'
import { Route as UzytkownicyUsernameRouteImport } from './routes/uzytkownicy.$username'
import { Route as ApiPublicSignupRouteImport } from './routes/api/public/signup'
import { Route as ApiPublicSetupTablesRouteImport } from './routes/api/public/setup-tables'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'

const ZarejestrujRoute = ZarejestrujRouteImport.update({
  id: '/zarejestruj',
  path: '/zarejestruj',
  getParentRoute: () => rootRouteImport,
} as any)
const ZalogujRoute = ZalogujRouteImport.update({
  id: '/zaloguj',
  path: '/zaloguj',
  getParentRoute: () => rootRouteImport,
} as any)
const UzytkownicyRoute = UzytkownicyRouteImport.update({
  id: '/uzytkownicy',
  path: '/uzytkownicy',
  getParentRoute: () => rootRouteImport,
} as any)
const UlepszRoute = UlepszRouteImport.update({
  id: '/ulepsz',
  path: '/ulepsz',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const DodajRoute = DodajRouteImport.update({
  id: '/dodaj',
  path: '/dodaj',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatekIdRoute = WatekIdRouteImport.update({
  id: '/watek/$id',
  path: '/watek/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UzytkownicyUsernameRoute = UzytkownicyUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => UzytkownicyRoute,
} as any)
const ApiPublicSignupRoute = ApiPublicSignupRouteImport.update({
  id: '/api/public/signup',
  path: '/api/public/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSetupTablesRoute = ApiPublicSetupTablesRouteImport.update({
  id: '/api/public/setup-tables',
  path: '/api/public/setup-tables',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dodaj': typeof DodajRoute
  '/galeria': typeof GaleriaRoute
  '/manager': typeof ManagerRoute
  '/profil': typeof ProfilRoute
  '/regulamin': typeof RegulaminRoute
  '/ulepsz': typeof UlepszRoute
  '/uzytkownicy': typeof UzytkownicyRouteWithChildren
  '/zaloguj': typeof ZalogujRoute
  '/zarejestruj': typeof ZarejestrujRoute
  '/uzytkownicy/$username': typeof UzytkownicyUsernameRoute
  '/watek/$id': typeof WatekIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/setup-tables': typeof ApiPublicSetupTablesRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dodaj': typeof DodajRoute
  '/galeria': typeof GaleriaRoute
  '/manager': typeof ManagerRoute
  '/profil': typeof ProfilRoute
  '/regulamin': typeof RegulaminRoute
  '/ulepsz': typeof UlepszRoute
  '/uzytkownicy': typeof UzytkownicyRouteWithChildren
  '/zaloguj': typeof ZalogujRoute
  '/zarejestruj': typeof ZarejestrujRoute
  '/uzytkownicy/$username': typeof UzytkownicyUsernameRoute
  '/watek/$id': typeof WatekIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/setup-tables': typeof ApiPublicSetupTablesRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dodaj': typeof DodajRoute
  '/galeria': typeof GaleriaRoute
  '/manager': typeof ManagerRoute
  '/profil': typeof ProfilRoute
  '/regulamin': typeof RegulaminRoute
  '/ulepsz': typeof UlepszRoute
  '/uzytkownicy': typeof UzytkownicyRouteWithChildren
  '/zaloguj': typeof ZalogujRoute
  '/zarejestruj': typeof ZarejestrujRoute
  '/uzytkownicy/$username': typeof UzytkownicyUsernameRoute
  '/watek/$id': typeof WatekIdRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/setup-tables': typeof ApiPublicSetupTablesRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dodaj'
    | '/galeria'
    | '/manager'
    | '/profil'
    | '/regulamin'
    | '/ulepsz'
    | '/uzytkownicy'
    | '/zaloguj'
    | '/zarejestruj'
    | '/uzytkownicy/$username'
    | '/watek/$id'
    | '/api/public/bootstrap-admin'
    | '/api/public/setup-tables'
    | '/api/public/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dodaj'
    | '/galeria'
    | '/manager'
    | '/profil'
    | '/regulamin'
    | '/ulepsz'
    | '/uzytkownicy'
    | '/zaloguj'
    | '/zarejestruj'
    | '/uzytkownicy/$username'
    | '/watek/$id'
    | '/api/public/bootstrap-admin'
    | '/api/public/setup-tables'
    | '/api/public/signup'
  id:
    | '__root__'
    | '/'
    | '/dodaj'
    | '/galeria'
    | '/manager'
    | '/profil'
    | '/regulamin'
    | '/ulepsz'
    | '/uzytkownicy'
    | '/zaloguj'
    | '/zarejestruj'
    | '/uzytkownicy/$username'
    | '/watek/$id'
    | '/api/public/bootstrap-admin'
    | '/api/public/setup-tables'
    | '/api/public/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DodajRoute: typeof DodajRoute
  GaleriaRoute: typeof GaleriaRoute
  ManagerRoute: typeof ManagerRoute
  ProfilRoute: typeof ProfilRoute
  RegulaminRoute: typeof RegulaminRoute
  UlepszRoute: typeof UlepszRoute
  UzytkownicyRoute: typeof UzytkownicyRouteWithChildren
  ZalogujRoute: typeof ZalogujRoute
  ZarejestrujRoute: typeof ZarejestrujRoute
  WatekIdRoute: typeof WatekIdRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ApiPublicSetupTablesRoute: typeof ApiPublicSetupTablesRoute
  ApiPublicSignupRoute: typeof ApiPublicSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zarejestruj': {
      id: '/zarejestruj'
      path: '/zarejestruj'
      fullPath: '/zarejestruj'
      preLoaderRoute: typeof ZarejestrujRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zaloguj': {
      id: '/zaloguj'
      path: '/zaloguj'
      fullPath: '/zaloguj'
      preLoaderRoute: typeof ZalogujRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uzytkownicy': {
      id: '/uzytkownicy'
      path: '/uzytkownicy'
      fullPath: '/uzytkownicy'
      preLoaderRoute: typeof UzytkownicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ulepsz': {
      id: '/ulepsz'
      path: '/ulepsz'
      fullPath: '/ulepsz'
      preLoaderRoute: typeof UlepszRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dodaj': {
      id: '/dodaj'
      path: '/dodaj'
      fullPath: '/dodaj'
      preLoaderRoute: typeof DodajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watek/$id': {
      id: '/watek/$id'
      path: '/watek/$id'
      fullPath: '/watek/$id'
      preLoaderRoute: typeof WatekIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uzytkownicy/$username': {
      id: '/uzytkownicy/$username'
      path: '/$username'
      fullPath: '/uzytkownicy/$username'
      preLoaderRoute: typeof UzytkownicyUsernameRouteImport
      parentRoute: typeof UzytkownicyRoute
    }
    '/api/public/signup': {
      id: '/api/public/signup'
      path: '/api/public/signup'
      fullPath: '/api/public/signup'
      preLoaderRoute: typeof ApiPublicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/setup-tables': {
      id: '/api/public/setup-tables'
      path: '/api/public/setup-tables'
      fullPath: '/api/public/setup-tables'
      preLoaderRoute: typeof ApiPublicSetupTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UzytkownicyRouteChildren {
  UzytkownicyUsernameRoute: typeof UzytkownicyUsernameRoute
}

const UzytkownicyRouteChildren: UzytkownicyRouteChildren = {
  UzytkownicyUsernameRoute: UzytkownicyUsernameRoute,
}

const UzytkownicyRouteWithChildren = UzytkownicyRoute._addFileChildren(
  UzytkownicyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DodajRoute: DodajRoute,
  GaleriaRoute: GaleriaRoute,
  ManagerRoute: ManagerRoute,
  ProfilRoute: ProfilRoute,
  RegulaminRoute: RegulaminRoute,
  UlepszRoute: UlepszRoute,
  UzytkownicyRoute: UzytkownicyRouteWithChildren,
  ZalogujRoute: ZalogujRoute,
  ZarejestrujRoute: ZarejestrujRoute,
  WatekIdRoute: WatekIdRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ApiPublicSetupTablesRoute: ApiPublicSetupTablesRoute,
  ApiPublicSignupRoute: ApiPublicSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
